// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type User struct {
	UserID       int32
	UserName     sql.NullString
	UserPassword sql.NullString
}
