// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: money.sql

package database

import (
	"context"
	"database/sql"
)

const createMoney = `-- name: CreateMoney :one
INSERT INTO money (
    mon_desc,
    amt,
    user_id ,
    mon_date
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING mon_id, mon_desc, amt, user_id, mon_date
`

type CreateMoneyParams struct {
	MonDesc sql.NullString
	Amt     sql.NullInt32
	UserID  sql.NullInt32
	MonDate sql.NullTime
}

func (q *Queries) CreateMoney(ctx context.Context, arg CreateMoneyParams) (Money, error) {
	row := q.db.QueryRowContext(ctx, createMoney,
		arg.MonDesc,
		arg.Amt,
		arg.UserID,
		arg.MonDate,
	)
	var i Money
	err := row.Scan(
		&i.MonID,
		&i.MonDesc,
		&i.Amt,
		&i.UserID,
		&i.MonDate,
	)
	return i, err
}
