// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_name,
    user_password
) VALUES (
    $1,
    $2
)
RETURNING user_id, user_name, user_password
`

type CreateUserParams struct {
	UserName     sql.NullString
	UserPassword sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.UserName, arg.UserPassword)
	var i User
	err := row.Scan(&i.UserID, &i.UserName, &i.UserPassword)
	return i, err
}
